# Generated by Django 3.2.4 on 2021-06-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
